[package]
name = "bamcut"
version = "0.1.0"
edition = "2021"

[dependencies]
clap = { version = "4.5.4", features = ["derive"] }
flate2 = "1.0.35"
log = "0.4.22"
pretty_env_logger = "0.5.0"
rust-htslib = "0.49.0"
